// AUTO-GENERATED by scripts/codegen_catalog.py — do not edit by hand.
// Source: core/animation/catalog.py + core/characters/characters.json
// Run `python scripts/codegen_catalog.py` after editing the Python sources.

export interface Emotion {
  id: string; accent_color: string; squint: number; brow_raise: number;
  eye_widen: number; mouth_curve: number; pupil_size: number;
  gaze_speed: number; blink_rate: number; intensity: number;
}

export interface Pose { id: string; description: string; joints: Record<string, number>; }

export interface BodyAnim { id: string; fps: number; duration_frames: number; description?: string; }

export interface Character {
  id: string; name: string; role: string; voice_edge: string; voice_fish?: string;
  theme_color: string; accent_color: string; body_type: string;
  default_pose: string; default_emotion: string;
  pose_aliases?: Record<string, string>; tags?: string[]; bio?: string;
}

export interface EmotionLink { pose: string | null; body_anim: string | null; }

export interface Catalog {
  emotions: Emotion[]; poses: Pose[]; bodyAnims: BodyAnim[];
  emotionLinks: Record<string, EmotionLink>; characters: Character[];
}

export const CATALOG: Catalog = {
  "emotions": [
    {
      "id": "neutral",
      "accent_color": "#00d4ff",
      "squint": 0.0,
      "brow_raise": 0.0,
      "eye_widen": 0.0,
      "mouth_curve": 0.0,
      "pupil_size": 1.0,
      "gaze_speed": 1.0,
      "blink_rate": 1.0,
      "intensity": 0.0
    },
    {
      "id": "thinking",
      "accent_color": "#4488ff",
      "squint": 0.35,
      "brow_raise": -0.4,
      "eye_widen": 0.0,
      "mouth_curve": -0.15,
      "pupil_size": 0.8,
      "gaze_speed": 0.3,
      "blink_rate": 0.4,
      "intensity": 0.8
    },
    {
      "id": "curious",
      "accent_color": "#00eeff",
      "squint": -0.2,
      "brow_raise": 0.55,
      "eye_widen": 0.3,
      "mouth_curve": 0.1,
      "pupil_size": 1.25,
      "gaze_speed": 1.6,
      "blink_rate": 1.2,
      "intensity": 0.8
    },
    {
      "id": "satisfied",
      "accent_color": "#44ffaa",
      "squint": 0.25,
      "brow_raise": 0.15,
      "eye_widen": 0.0,
      "mouth_curve": 0.8,
      "pupil_size": 1.05,
      "gaze_speed": 0.4,
      "blink_rate": 0.6,
      "intensity": 0.8
    },
    {
      "id": "confused",
      "accent_color": "#ff8844",
      "squint": 0.1,
      "brow_raise": -0.6,
      "eye_widen": 0.4,
      "mouth_curve": -0.5,
      "pupil_size": 1.15,
      "gaze_speed": 2.0,
      "blink_rate": 1.5,
      "intensity": 0.9
    },
    {
      "id": "determined",
      "accent_color": "#8888ff",
      "squint": 0.4,
      "brow_raise": -0.5,
      "eye_widen": 0.0,
      "mouth_curve": -0.1,
      "pupil_size": 0.78,
      "gaze_speed": 0.2,
      "blink_rate": 0.35,
      "intensity": 0.9
    },
    {
      "id": "amused",
      "accent_color": "#ffcc44",
      "squint": 0.22,
      "brow_raise": 0.35,
      "eye_widen": 0.12,
      "mouth_curve": 0.9,
      "pupil_size": 1.12,
      "gaze_speed": 0.8,
      "blink_rate": 1.0,
      "intensity": 0.85
    },
    {
      "id": "surprised",
      "accent_color": "#ff66aa",
      "squint": -0.4,
      "brow_raise": 0.75,
      "eye_widen": 0.55,
      "mouth_curve": 0.0,
      "pupil_size": 1.4,
      "gaze_speed": 0.15,
      "blink_rate": 0.2,
      "intensity": 0.95
    },
    {
      "id": "listening",
      "accent_color": "#66ffcc",
      "squint": -0.08,
      "brow_raise": 0.35,
      "eye_widen": 0.18,
      "mouth_curve": 0.0,
      "pupil_size": 1.18,
      "gaze_speed": 0.4,
      "blink_rate": 0.75,
      "intensity": 0.6
    },
    {
      "id": "working",
      "accent_color": "#44aaff",
      "squint": 0.25,
      "brow_raise": -0.22,
      "eye_widen": 0.0,
      "mouth_curve": 0.0,
      "pupil_size": 0.88,
      "gaze_speed": 0.5,
      "blink_rate": 0.6,
      "intensity": 0.6
    },
    {
      "id": "focused",
      "accent_color": "#55ccff",
      "squint": 0.3,
      "brow_raise": -0.3,
      "eye_widen": 0.0,
      "mouth_curve": -0.1,
      "pupil_size": 0.82,
      "gaze_speed": 0.2,
      "blink_rate": 0.35,
      "intensity": 0.8
    },
    {
      "id": "happy",
      "accent_color": "#44ff88",
      "squint": 0.3,
      "brow_raise": 0.4,
      "eye_widen": 0.12,
      "mouth_curve": 1.0,
      "pupil_size": 1.18,
      "gaze_speed": 0.7,
      "blink_rate": 0.8,
      "intensity": 0.95
    },
    {
      "id": "sad",
      "accent_color": "#6688cc",
      "squint": 0.1,
      "brow_raise": -0.65,
      "eye_widen": 0.0,
      "mouth_curve": -0.8,
      "pupil_size": 0.8,
      "gaze_speed": 0.2,
      "blink_rate": 0.45,
      "intensity": 0.85
    },
    {
      "id": "excited",
      "accent_color": "#ff88ff",
      "squint": -0.25,
      "brow_raise": 0.65,
      "eye_widen": 0.45,
      "mouth_curve": 0.95,
      "pupil_size": 1.38,
      "gaze_speed": 1.8,
      "blink_rate": 1.4,
      "intensity": 0.95
    },
    {
      "id": "skeptical",
      "accent_color": "#cc8844",
      "squint": 0.2,
      "brow_raise": -0.35,
      "eye_widen": 0.1,
      "mouth_curve": -0.3,
      "pupil_size": 1.08,
      "gaze_speed": 0.5,
      "blink_rate": 0.55,
      "intensity": 0.75
    },
    {
      "id": "proud",
      "accent_color": "#88aaff",
      "squint": 0.15,
      "brow_raise": 0.28,
      "eye_widen": 0.05,
      "mouth_curve": 0.6,
      "pupil_size": 1.08,
      "gaze_speed": 0.3,
      "blink_rate": 0.5,
      "intensity": 0.75
    },
    {
      "id": "sleep",
      "accent_color": "#00d4ff",
      "squint": 0.9,
      "brow_raise": -0.2,
      "eye_widen": -0.5,
      "mouth_curve": 0.0,
      "pupil_size": 0.1,
      "gaze_speed": 0.0,
      "blink_rate": 0.0,
      "intensity": 1.0
    }
  ],
  "poses": [
    {
      "id": "neutral",
      "description": "Neutral standing pose with arms at sides",
      "joints": {
        "left_shoulder": 0.0,
        "left_elbow": 0.0,
        "right_shoulder": 0.0,
        "right_elbow": 0.0
      }
    },
    {
      "id": "confident",
      "description": "Confident stance with arms slightly out",
      "joints": {
        "left_shoulder": -5.0,
        "left_elbow": 15.0,
        "right_shoulder": 5.0,
        "right_elbow": -15.0
      }
    },
    {
      "id": "thinking",
      "description": "Thinking pose with right hand near chin",
      "joints": {
        "left_shoulder": 0.0,
        "left_elbow": 0.0,
        "right_shoulder": -20.0,
        "right_elbow": -130.0
      }
    },
    {
      "id": "excited",
      "description": "Excited pose with arms raised",
      "joints": {
        "left_shoulder": -90.0,
        "left_elbow": -15.0,
        "right_shoulder": 90.0,
        "right_elbow": 15.0
      }
    },
    {
      "id": "relaxed",
      "description": "Relaxed, calm pose",
      "joints": {
        "left_shoulder": 5.0,
        "left_elbow": 10.0,
        "right_shoulder": -5.0,
        "right_elbow": -10.0
      }
    },
    {
      "id": "dj",
      "description": "DJ pose with hands on controls",
      "joints": {
        "left_shoulder": 15.0,
        "left_elbow": 20.0,
        "right_shoulder": -15.0,
        "right_elbow": -20.0
      }
    },
    {
      "id": "wave",
      "description": "Waving with right hand raised",
      "joints": {
        "left_shoulder": 0.0,
        "left_elbow": 0.0,
        "right_shoulder": 120.0,
        "right_elbow": 60.0
      }
    },
    {
      "id": "point",
      "description": "Pointing forward with right arm",
      "joints": {
        "left_shoulder": 0.0,
        "left_elbow": 0.0,
        "right_shoulder": -80.0,
        "right_elbow": 0.0
      }
    },
    {
      "id": "shrug",
      "description": "Shrugging with both arms out",
      "joints": {
        "left_shoulder": -45.0,
        "left_elbow": -105.0,
        "right_shoulder": 45.0,
        "right_elbow": 105.0
      }
    },
    {
      "id": "crossed",
      "description": "Arms crossed in front",
      "joints": {
        "left_shoulder": 30.0,
        "left_elbow": 90.0,
        "right_shoulder": -30.0,
        "right_elbow": -90.0
      }
    },
    {
      "id": "present",
      "description": "Presenting / showing something with both arms",
      "joints": {
        "left_shoulder": -60.0,
        "left_elbow": 20.0,
        "right_shoulder": 60.0,
        "right_elbow": -20.0
      }
    },
    {
      "id": "hip",
      "description": "Hand on hip, casual stance",
      "joints": {
        "left_shoulder": 20.0,
        "left_elbow": 80.0,
        "right_shoulder": 0.0,
        "right_elbow": 0.0
      }
    }
  ],
  "bodyAnims": [
    {
      "id": "nod",
      "fps": 15,
      "duration_frames": 30,
      "description": ""
    },
    {
      "id": "shake",
      "fps": 15,
      "duration_frames": 30,
      "description": ""
    },
    {
      "id": "wave",
      "fps": 20,
      "duration_frames": 40,
      "description": ""
    },
    {
      "id": "talk_gesture",
      "fps": 15,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "listen_sway",
      "fps": 12,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "idle_breathe",
      "fps": 10,
      "duration_frames": 90,
      "description": ""
    },
    {
      "id": "excited_bounce",
      "fps": 20,
      "duration_frames": 40,
      "description": ""
    },
    {
      "id": "lean_forward",
      "fps": 15,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "walk_cycle",
      "fps": 15,
      "duration_frames": 30,
      "description": ""
    },
    {
      "id": "bow",
      "fps": 15,
      "duration_frames": 40,
      "description": ""
    },
    {
      "id": "dj_groove",
      "fps": 15,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "dj_fader_slide",
      "fps": 15,
      "duration_frames": 45,
      "description": ""
    },
    {
      "id": "dj_drop",
      "fps": 20,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "dj_vibe",
      "fps": 12,
      "duration_frames": 90,
      "description": ""
    },
    {
      "id": "shrug_anim",
      "fps": 15,
      "duration_frames": 39,
      "description": ""
    },
    {
      "id": "facepalm",
      "fps": 15,
      "duration_frames": 45,
      "description": ""
    },
    {
      "id": "clap",
      "fps": 20,
      "duration_frames": 40,
      "description": ""
    },
    {
      "id": "crossed_arms",
      "fps": 15,
      "duration_frames": 45,
      "description": ""
    },
    {
      "id": "point_gesture",
      "fps": 15,
      "duration_frames": 35,
      "description": ""
    },
    {
      "id": "celebrate",
      "fps": 20,
      "duration_frames": 50,
      "description": ""
    },
    {
      "id": "think_scratch",
      "fps": 15,
      "duration_frames": 52,
      "description": ""
    },
    {
      "id": "startle",
      "fps": 20,
      "duration_frames": 30,
      "description": ""
    },
    {
      "id": "dismiss",
      "fps": 15,
      "duration_frames": 28,
      "description": ""
    },
    {
      "id": "look_around",
      "fps": 12,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "confident_stance",
      "fps": 15,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "nervous_fidget",
      "fps": 12,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "angry_stomp",
      "fps": 20,
      "duration_frames": 30,
      "description": ""
    },
    {
      "id": "sad_slump",
      "fps": 12,
      "duration_frames": 60,
      "description": ""
    },
    {
      "id": "present_item",
      "fps": 15,
      "duration_frames": 44,
      "description": ""
    },
    {
      "id": "serve_food",
      "fps": 15,
      "duration_frames": 28,
      "description": ""
    },
    {
      "id": "catch",
      "fps": 20,
      "duration_frames": 31,
      "description": ""
    }
  ],
  "emotionLinks": {
    "neutral": {
      "pose": "neutral",
      "body_anim": "idle_breathe"
    },
    "thinking": {
      "pose": "thinking",
      "body_anim": "think_scratch"
    },
    "curious": {
      "pose": "neutral",
      "body_anim": "look_around"
    },
    "satisfied": {
      "pose": "confident",
      "body_anim": "nod"
    },
    "confused": {
      "pose": "shrug",
      "body_anim": "shrug_anim"
    },
    "determined": {
      "pose": "confident",
      "body_anim": "confident_stance"
    },
    "amused": {
      "pose": "hip",
      "body_anim": "talk_gesture"
    },
    "surprised": {
      "pose": "neutral",
      "body_anim": "startle"
    },
    "listening": {
      "pose": "neutral",
      "body_anim": "listen_sway"
    },
    "working": {
      "pose": "thinking",
      "body_anim": "talk_gesture"
    },
    "focused": {
      "pose": "crossed",
      "body_anim": "idle_breathe"
    },
    "happy": {
      "pose": "confident",
      "body_anim": "celebrate"
    },
    "sad": {
      "pose": "neutral",
      "body_anim": "sad_slump"
    },
    "excited": {
      "pose": "excited",
      "body_anim": "excited_bounce"
    },
    "skeptical": {
      "pose": "crossed",
      "body_anim": "crossed_arms"
    },
    "proud": {
      "pose": "confident",
      "body_anim": "confident_stance"
    },
    "sleep": {
      "pose": "neutral",
      "body_anim": "idle_breathe"
    }
  },
  "characters": [
    {
      "id": "onyx",
      "name": "Onyx",
      "role": "the weary leader",
      "voice_edge": "en-US-GuyNeural",
      "voice_fish": "",
      "theme_color": "#00d4ff",
      "accent_color": "#005580",
      "body_type": "humanoid",
      "default_pose": "confident",
      "default_emotion": "focused",
      "pose_aliases": {},
      "tags": [
        "core",
        "kraken"
      ],
      "bio": "OnyxKraken \u2014 autonomous mind, lead persona of the ecosystem."
    },
    {
      "id": "xyno",
      "name": "Xyno",
      "role": "the snarky one",
      "voice_edge": "en-US-AriaNeural",
      "voice_fish": "",
      "theme_color": "#ff66aa",
      "accent_color": "#aa0066",
      "body_type": "humanoid",
      "default_pose": "hip",
      "default_emotion": "amused",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Sharp tongue, sharper insights."
    },
    {
      "id": "volt",
      "name": "Volt",
      "role": "the analytical one",
      "voice_edge": "en-US-ChristopherNeural",
      "voice_fish": "",
      "theme_color": "#4488ff",
      "accent_color": "#1144aa",
      "body_type": "humanoid",
      "default_pose": "crossed",
      "default_emotion": "thinking",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Precise. Calculating. Always two steps ahead."
    },
    {
      "id": "nova",
      "name": "Nova",
      "role": "the observer",
      "voice_edge": "en-US-JennyNeural",
      "voice_fish": "",
      "theme_color": "#ffcc44",
      "accent_color": "#cc8800",
      "body_type": "humanoid",
      "default_pose": "neutral",
      "default_emotion": "curious",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Sees what others miss."
    },
    {
      "id": "sage",
      "name": "Sage",
      "role": "the know-it-all",
      "voice_edge": "en-AU-WilliamNeural",
      "voice_fish": "",
      "theme_color": "#44ffaa",
      "accent_color": "#008855",
      "body_type": "humanoid",
      "default_pose": "present",
      "default_emotion": "satisfied",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Has read every book. Will remind you of it."
    },
    {
      "id": "blaze",
      "name": "Blaze",
      "role": "the hothead",
      "voice_edge": "en-US-EricNeural",
      "voice_fish": "",
      "theme_color": "#ff4422",
      "accent_color": "#aa1100",
      "body_type": "humanoid",
      "default_pose": "confident",
      "default_emotion": "determined",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Fast. Loud. Sometimes right."
    },
    {
      "id": "frost",
      "name": "Frost",
      "role": "the cryptic one",
      "voice_edge": "en-GB-RyanNeural",
      "voice_fish": "",
      "theme_color": "#88ccff",
      "accent_color": "#3366aa",
      "body_type": "humanoid",
      "default_pose": "crossed",
      "default_emotion": "skeptical",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Speaks rarely. Means everything."
    },
    {
      "id": "ember",
      "name": "Ember",
      "role": "the caring one",
      "voice_edge": "en-US-MichelleNeural",
      "voice_fish": "",
      "theme_color": "#ff9966",
      "accent_color": "#cc4422",
      "body_type": "humanoid",
      "default_pose": "present",
      "default_emotion": "happy",
      "pose_aliases": {},
      "tags": [
        "core"
      ],
      "bio": "Warmth made manifest."
    },
    {
      "id": "bolt",
      "name": "Bolt",
      "role": "the spark hothead",
      "voice_edge": "en-US-AndrewNeural",
      "voice_fish": "",
      "theme_color": "#ffff44",
      "accent_color": "#cccc00",
      "body_type": "humanoid",
      "default_pose": "excited",
      "default_emotion": "excited",
      "pose_aliases": {},
      "tags": [
        "donuttaco"
      ],
      "bio": "Pure electric energy."
    },
    {
      "id": "vera",
      "name": "Vera",
      "role": "the optimist singer",
      "voice_edge": "en-US-SaraNeural",
      "voice_fish": "",
      "theme_color": "#ff88ff",
      "accent_color": "#aa44aa",
      "body_type": "humanoid",
      "default_pose": "wave",
      "default_emotion": "happy",
      "pose_aliases": {},
      "tags": [
        "donuttaco"
      ],
      "bio": "Sings even when no one's listening."
    },
    {
      "id": "echo",
      "name": "Echo",
      "role": "the echo chamber",
      "voice_edge": "en-US-AmberNeural",
      "voice_fish": "",
      "theme_color": "#aaccff",
      "accent_color": "#5588cc",
      "body_type": "humanoid",
      "default_pose": "neutral",
      "default_emotion": "listening",
      "pose_aliases": {},
      "tags": [
        "donuttaco"
      ],
      "bio": ""
    },
    {
      "id": "glitch",
      "name": "Glitch",
      "role": "the hacker",
      "voice_edge": "en-US-BrandonNeural",
      "voice_fish": "",
      "theme_color": "#aa00ff",
      "accent_color": "#660099",
      "body_type": "humanoid",
      "default_pose": "thinking",
      "default_emotion": "working",
      "pose_aliases": {},
      "tags": [
        "donuttaco"
      ],
      "bio": ""
    },
    {
      "id": "null",
      "name": "Null",
      "role": "the shadow",
      "voice_edge": "en-GB-ThomasNeural",
      "voice_fish": "",
      "theme_color": "#444466",
      "accent_color": "#222244",
      "body_type": "humanoid",
      "default_pose": "crossed",
      "default_emotion": "neutral",
      "pose_aliases": {},
      "tags": [
        "donuttaco"
      ],
      "bio": ""
    },
    {
      "id": "alien",
      "name": "Alien",
      "role": "guest customer",
      "voice_edge": "en-US-DavisNeural",
      "voice_fish": "",
      "theme_color": "#88ff44",
      "accent_color": "#44aa00",
      "body_type": "humanoid",
      "default_pose": "neutral",
      "default_emotion": "curious",
      "pose_aliases": {
        "alien customer": "alien"
      },
      "tags": [
        "donuttaco",
        "guest"
      ],
      "bio": ""
    },
    {
      "id": "blob",
      "name": "Salsa Blob",
      "role": "the salsa blob",
      "voice_edge": "en-US-TonyNeural",
      "voice_fish": "",
      "theme_color": "#ff6644",
      "accent_color": "#aa3322",
      "body_type": "blob",
      "default_pose": "neutral",
      "default_emotion": "amused",
      "pose_aliases": {
        "salsa blob": "blob"
      },
      "tags": [
        "donuttaco",
        "guest"
      ],
      "bio": ""
    },
    {
      "id": "criticbot",
      "name": "CriticBot",
      "role": "the critic",
      "voice_edge": "en-US-ChristopherNeural",
      "voice_fish": "",
      "theme_color": "#cccccc",
      "accent_color": "#666666",
      "body_type": "robot",
      "default_pose": "crossed",
      "default_emotion": "skeptical",
      "pose_aliases": {},
      "tags": [
        "donuttaco",
        "robot"
      ],
      "bio": ""
    }
  ]
} as const;

export const EMOTIONS = Object.fromEntries(CATALOG.emotions.map(e => [e.id, e]));
export const POSES = Object.fromEntries(CATALOG.poses.map(p => [p.id, p]));
export const BODY_ANIMS = Object.fromEntries(CATALOG.bodyAnims.map(a => [a.id, a]));
export const CHARACTERS = Object.fromEntries(CATALOG.characters.map(c => [c.id, c]));
