"""Self-Improvement Engine — OnyxKraken learns from failures and generates new capabilities.

Inspired by AlphaEvolve/EVERA concepts, adapted for OnyxKraken's desktop automation focus.

Workflow:
  1. Track failed tasks and their error patterns
  2. Analyze failures to identify capability gaps (missing app modules, action patterns)
  3. Generate new app modules or action handlers using a coder model
  4. Test generated modules for basic validity
  5. Deploy successful modules into the registry

Storage: JSON file at data/self_improvement.json
"""

import hashlib
import json
import os
import time
from dataclasses import dataclass
from pathlib import Path

from log import get_logger

_log = get_logger("self_improve")
from typing import Any, Optional

try:
    from agent.model_router import router
except ImportError:
    router = None
try:
    from memory.base_store import BaseJsonStore
except ImportError:
    BaseJsonStore = None


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class FailedTask:
    """Record of a failed task for analysis."""
    id: str
    goal: str
    error: str
    app_name: str
    actions_tried: list[str]
    timestamp: float
    analyzed: bool = False
    gap_type: str = ""  # "missing_app_module", "action_failure", "planning_error"


@dataclass
class SkillGap:
    """Identified capability that OnyxKraken is missing."""
    id: str
    description: str
    gap_type: str  # "app_module", "action_handler", "planning_pattern"
    example_tasks: list[str]
    priority: float  # 0-1 based on frequency
    resolved: bool = False
    generated_artifact: str = ""  # path to generated file


@dataclass
class GeneratedModule:
    """A module generated by the self-improvement system."""
    id: str
    name: str
    description: str
    code: str
    gap_id: str
    generated_at: float
    tested: bool = False
    test_passed: bool = False
    deployed: bool = False
    test_output: str = ""


# ---------------------------------------------------------------------------
# Persistence (JSON-based, matching OnyxKraken's style)
# ---------------------------------------------------------------------------

_DB_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "self_improvement.json")

_DEFAULT_DB = {
    "failed_tasks": [],
    "skill_gaps": [],
    "generated_modules": [],
    "improvement_runs": [],
    "stats": {
        "total_failures_analyzed": 0,
        "total_gaps_identified": 0,
        "total_modules_generated": 0,
        "total_modules_deployed": 0,
    }
}

MAX_FAILURES = 200
MAX_GAPS = 50
MAX_GENERATED = 50


class _Store(BaseJsonStore):
    """Simple JSON persistence for improvement data."""

    def __init__(self, path: str = _DB_FILE):
        super().__init__(path, _DEFAULT_DB)

    def save(self):
        self._save()


# ---------------------------------------------------------------------------
# Self-Improvement Engine
# ---------------------------------------------------------------------------

class SelfImprovementEngine:
    """Analyzes failures, identifies gaps, and generates new capabilities.

    Uses the reasoning model to analyze failures and the coder/planner model
    to generate new app modules or action patterns.
    """

    def __init__(self):
        self._store = _Store()
        self._apps_generated_dir = Path(os.path.dirname(os.path.dirname(__file__))) / "apps" / "generated"
        self._apps_generated_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Record failures (called by orchestrator after task completion)
    # ------------------------------------------------------------------

    def record_failure(self, goal: str, error: str, app_name: str,
                       actions_tried: list[str]):
        """Record a failed task for later analysis."""
        failure_id = hashlib.md5(f"{goal}:{error}:{time.time()}".encode()).hexdigest()[:12]
        entry = {
            "id": failure_id,
            "goal": goal,
            "error": error[:500],
            "app_name": app_name,
            "actions_tried": actions_tried[:20],
            "timestamp": time.time(),
            "analyzed": False,
            "gap_type": "",
        }
        self._store.data["failed_tasks"].append(entry)
        # Cap
        if len(self._store.data["failed_tasks"]) > MAX_FAILURES:
            self._store.data["failed_tasks"] = self._store.data["failed_tasks"][-MAX_FAILURES:]
        self._store.save()
        _log.info(f"Recorded failure: {goal[:60]}...")

    # ------------------------------------------------------------------
    # Analyze failures → identify gaps
    # ------------------------------------------------------------------

    def analyze_failures(self) -> list[dict]:
        """Analyze unanalyzed failures and identify capability gaps.

        Returns list of newly identified gaps.
        """
        unanalyzed = [f for f in self._store.data["failed_tasks"] if not f["analyzed"]]
        if not unanalyzed:
            _log.info("No unanalyzed failures.")
            return []

        _log.info(f"Analyzing {len(unanalyzed)} failures...")

        # Group failures by similarity
        failure_summary = "\n".join(
            f"- Goal: \"{f['goal'][:80]}\" | App: {f['app_name']} | "
            f"Error: {f['error'][:100]} | Actions: {', '.join(f['actions_tried'][:5])}"
            for f in unanalyzed[:20]
        )

        prompt = (
            "You are analyzing failures from a Windows desktop automation agent called OnyxKraken.\n"
            "It can: click, type, key_press, scroll, launch apps, read/write files, run commands, "
            "run Python, run Blender scripts, and interact with apps via accessibility tree + vision.\n\n"
            "It has app-specific modules for known apps. When an app module is missing, it auto-generates "
            "one by inspecting the window's accessibility tree.\n\n"
            f"RECENT FAILURES:\n{failure_summary}\n\n"
            "Identify CAPABILITY GAPS — what is OnyxKraken missing that caused these failures?\n\n"
            "For each gap, classify it as one of:\n"
            "- 'app_module': Needs a better/new app module for a specific application\n"
            "- 'action_handler': Needs a new type of action it can't currently perform\n"
            "- 'planning_pattern': Needs a better planning strategy for a category of tasks\n\n"
            "Respond with ONLY a JSON array of gaps:\n"
            '[{"description": "what is missing", "gap_type": "app_module|action_handler|planning_pattern", '
            '"example_tasks": ["task that would benefit"], "priority": 0.0-1.0}]\n'
            "If no real gaps exist (just LLM flakiness), return [].\n"
            "Output ONLY the JSON."
        )

        try:
            raw = router.get_content("reasoning", [{"role": "user", "content": prompt}])

            # Parse JSON array
            gaps = []
            start = raw.find("[")
            end = raw.rfind("]") + 1
            if start >= 0 and end > start:
                gaps = json.loads(raw[start:end])

            # Mark failures as analyzed
            for f in unanalyzed:
                f["analyzed"] = True

            # Store new gaps
            new_gaps = []
            for gap_data in gaps:
                if not isinstance(gap_data, dict) or "description" not in gap_data:
                    continue
                gap_id = hashlib.md5(gap_data["description"].encode()).hexdigest()[:12]
                # Skip duplicates
                existing_ids = {g["id"] for g in self._store.data["skill_gaps"]}
                if gap_id in existing_ids:
                    continue
                gap_entry = {
                    "id": gap_id,
                    "description": gap_data["description"],
                    "gap_type": gap_data.get("gap_type", "action_handler"),
                    "example_tasks": gap_data.get("example_tasks", []),
                    "priority": min(1.0, max(0.0, gap_data.get("priority", 0.5))),
                    "resolved": False,
                    "generated_artifact": "",
                    "detected_at": time.time(),
                }
                self._store.data["skill_gaps"].append(gap_entry)
                new_gaps.append(gap_entry)

            # Cap
            if len(self._store.data["skill_gaps"]) > MAX_GAPS:
                self._store.data["skill_gaps"] = self._store.data["skill_gaps"][-MAX_GAPS:]

            self._store.data["stats"]["total_failures_analyzed"] += len(unanalyzed)
            self._store.data["stats"]["total_gaps_identified"] += len(new_gaps)
            self._store.save()

            _log.info(f"Identified {len(new_gaps)} new capability gaps.")
            for g in new_gaps:
                _log.info(f"  [{g['gap_type']}] {g['description']} (priority: {g['priority']:.1f})")

            return new_gaps

        except Exception as e:
            _log.error(f"Analysis failed: {e}")
            return []

    # ------------------------------------------------------------------
    # Generate new app modules for identified gaps
    # ------------------------------------------------------------------

    def generate_for_gap(self, gap: dict) -> Optional[dict]:
        """Generate a new app module or action pattern for a skill gap.

        Returns the generated module entry dict, or None.
        """
        gap_type = gap.get("gap_type", "")
        description = gap.get("description", "")

        if gap_type == "app_module":
            return self._generate_app_module(gap)
        elif gap_type == "action_handler":
            return self._generate_action_handler(gap)
        elif gap_type == "planning_pattern":
            # Planning patterns are stored as JSON advice, not code
            return self._generate_planning_advice(gap)
        else:
            _log.warning(f"Unknown gap type: {gap_type}")
            return None

    def _generate_app_module(self, gap: dict) -> Optional[dict]:
        """Generate a new DynamicModule JSON config for an app."""
        description = gap["description"]
        examples = gap.get("example_tasks", [])

        prompt = (
            "You are generating a Windows application module config for a desktop automation agent.\n\n"
            f"GAP: {description}\n"
            f"EXAMPLE TASKS: {', '.join(examples[:3])}\n\n"
            "Generate a JSON config for this application module. Be accurate and practical.\n\n"
            "Required JSON format:\n"
            "{\n"
            '  "app_name": "short_lowercase_name",\n'
            '  "window_title_hint": "substring that identifies this app in window titles",\n'
            '  "launch_command": "executable.exe or null",\n'
            '  "desktop_shortcut": "shortcut name or null",\n'
            '  "is_chat_app": false,\n'
            '  "context_prompt": "Description of the app and its key UI elements for automation",\n'
            '  "known_elements": [\n'
            '    {"name": "element", "control_type": "Button", "description": "what it does"}\n'
            "  ]\n"
            "}\n\n"
            "Output ONLY the JSON."
        )

        try:
            raw = router.get_content("planner", [{"role": "user", "content": prompt}])
            cfg = self._extract_json_object(raw)
            if cfg is None or "app_name" not in cfg:
                _log.warning(f"Failed to generate app module config.")
                return None

            # Validate and save
            cfg.setdefault("launch_command", None)
            cfg.setdefault("desktop_shortcut", None)
            cfg.setdefault("is_chat_app", False)
            cfg.setdefault("context_prompt", "")
            cfg.setdefault("known_elements", [])

            config_path = self._apps_generated_dir / f"{cfg['app_name']}.json"
            with open(config_path, "w", encoding="utf-8") as f:
                json.dump(cfg, f, indent=2)

            module_id = hashlib.md5(f"{cfg['app_name']}:{time.time()}".encode()).hexdigest()[:12]
            entry = {
                "id": module_id,
                "name": cfg["app_name"],
                "description": description,
                "code": json.dumps(cfg, indent=2),
                "gap_id": gap["id"],
                "generated_at": time.time(),
                "tested": True,
                "test_passed": True,  # JSON configs are valid by construction
                "deployed": True,
                "test_output": f"Saved to {config_path}",
            }

            self._store.data["generated_modules"].append(entry)
            gap["resolved"] = True
            gap["generated_artifact"] = str(config_path)
            self._store.data["stats"]["total_modules_generated"] += 1
            self._store.data["stats"]["total_modules_deployed"] += 1
            self._store.save()

            _log.info(f"Generated app module: {cfg['app_name']} → {config_path}")
            return entry

        except Exception as e:
            _log.error(f"App module generation failed: {e}")
            return None

    def _generate_action_handler(self, gap: dict) -> Optional[dict]:
        """Generate advice or a code snippet for a new action capability."""
        description = gap["description"]

        prompt = (
            "You are helping a Windows desktop automation agent add a new capability.\n\n"
            f"MISSING CAPABILITY: {description}\n\n"
            "The agent can currently: click elements, type text, press keys, scroll, "
            "launch apps, read/write files, run shell commands, run Python scripts, "
            "run Blender scripts, manage clipboard, and focus windows.\n\n"
            "Suggest a concrete implementation approach:\n"
            "1. Can this be done by combining existing actions differently?\n"
            "2. Does it need a new action handler? If so, what would it do?\n"
            "3. What Python libraries would be needed?\n\n"
            "Respond with a JSON object:\n"
            '{"approach": "description of how to implement this", '
            '"needs_new_action": true/false, '
            '"action_name": "new_action_name or null", '
            '"libraries_needed": ["lib1"], '
            '"example_usage": "how the agent would use this"}\n'
            "Output ONLY the JSON."
        )

        try:
            raw = router.get_content("reasoning", [{"role": "user", "content": prompt}])
            advice = self._extract_json_object(raw)
            if advice is None:
                return None

            module_id = hashlib.md5(f"action:{description}:{time.time()}".encode()).hexdigest()[:12]
            entry = {
                "id": module_id,
                "name": advice.get("action_name", "advice"),
                "description": description,
                "code": json.dumps(advice, indent=2),
                "gap_id": gap["id"],
                "generated_at": time.time(),
                "tested": False,
                "test_passed": False,
                "deployed": False,
                "test_output": "",
            }

            self._store.data["generated_modules"].append(entry)
            self._store.save()

            _log.info(f"Generated action advice: {advice.get('approach', '')[:80]}...")
            return entry

        except Exception as e:
            _log.error(f"Action handler generation failed: {e}")
            return None

    def _generate_planning_advice(self, gap: dict) -> Optional[dict]:
        """Generate improved planning strategies."""
        description = gap["description"]

        prompt = (
            f"A desktop automation agent keeps failing at: {description}\n\n"
            "Suggest a better planning strategy as a JSON object:\n"
            '{"strategy": "description", "steps_template": ["step1", "step2"], '
            '"common_pitfalls": ["pitfall1"], "tips": ["tip1"]}\n'
            "Output ONLY the JSON."
        )

        try:
            raw = router.get_content("reasoning", [{"role": "user", "content": prompt}])
            advice = self._extract_json_object(raw)
            if advice is None:
                return None

            module_id = hashlib.md5(f"plan:{description}:{time.time()}".encode()).hexdigest()[:12]
            entry = {
                "id": module_id,
                "name": "planning_advice",
                "description": description,
                "code": json.dumps(advice, indent=2),
                "gap_id": gap["id"],
                "generated_at": time.time(),
                "tested": False,
                "test_passed": False,
                "deployed": False,
                "test_output": "",
            }

            self._store.data["generated_modules"].append(entry)
            gap["resolved"] = True
            self._store.save()

            _log.info(f"Generated planning advice for: {description[:60]}...")
            return entry

        except Exception as e:
            _log.error(f"Planning advice generation failed: {e}")
            return None

    # ------------------------------------------------------------------
    # Run full improvement cycle
    # ------------------------------------------------------------------

    def run_improvement_cycle(self) -> dict:
        """Run a full analyze → generate → deploy cycle.

        Returns summary dict.
        """
        _log.info(f"{'='*60}")
        _log.info(f"  OnyxKraken Self-Improvement Cycle")
        _log.info(f"{'='*60}")

        # Step 1: Analyze failures
        new_gaps = self.analyze_failures()

        # Step 2: Generate for unresolved gaps (prioritized)
        unresolved = [g for g in self._store.data["skill_gaps"]
                      if not g.get("resolved")]
        unresolved.sort(key=lambda g: g.get("priority", 0), reverse=True)

        generated = []
        for gap in unresolved[:3]:  # Process top 3 gaps per cycle
            _log.info(f"Addressing gap: {gap['description'][:60]}...")
            result = self.generate_for_gap(gap)
            if result:
                generated.append(result)

        # Record run
        run_entry = {
            "timestamp": time.time(),
            "failures_analyzed": len([f for f in self._store.data["failed_tasks"] if f["analyzed"]]),
            "gaps_found": len(new_gaps),
            "modules_generated": len(generated),
        }
        self._store.data["improvement_runs"].append(run_entry)
        self._store.save()

        summary = {
            "gaps_identified": len(new_gaps),
            "modules_generated": len(generated),
            "total_unresolved_gaps": len(unresolved) - len(generated),
        }

        _log.info(f"Cycle complete: {summary}")
        return summary

    # ------------------------------------------------------------------
    # Stats / inspection
    # ------------------------------------------------------------------

    def get_stats(self) -> dict:
        """Get self-improvement statistics."""
        return {
            **self._store.data["stats"],
            "unanalyzed_failures": sum(1 for f in self._store.data["failed_tasks"] if not f["analyzed"]),
            "unresolved_gaps": sum(1 for g in self._store.data["skill_gaps"] if not g.get("resolved")),
            "total_improvement_runs": len(self._store.data["improvement_runs"]),
        }

    def get_unresolved_gaps(self) -> list[dict]:
        """Get all unresolved capability gaps."""
        return [g for g in self._store.data["skill_gaps"] if not g.get("resolved")]

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_json_object(raw: str) -> Optional[dict]:
        """Extract the first JSON object from raw text."""
        from core.utils import extract_json
        return extract_json(raw)


# ---------------------------------------------------------------------------
# Singleton (delegates to service registry)
# ---------------------------------------------------------------------------

def get_improvement_engine() -> SelfImprovementEngine:
    """Get or create the global self-improvement engine."""
    from core.service_registry import services
    if not services.has("self_improvement"):
        services.register_factory("self_improvement", SelfImprovementEngine)
    return services.get("self_improvement", SelfImprovementEngine)
